---
gw_config:
  translate_dscp: true
  conntrack_max: 300000

gw_whitelist: []

gw_blacklist:
  hosts: []
  ports: []

gw_nameservers: []

gw_overrides: {}
gw_routes: {}
gw_ipset_routes: {}
gw_force_routes: {}
gw_host_priority: {}

gw_trashing:
  - [ 'browse', 'download', '4000000', 'both' ]
  - [ 'prio1', 'trash', '41943040', 'original' ]
  - [ 'prio1', 'trash', '104857600', 'reply' ]
  - [ 'prio2', 'trash', '41943040', 'original' ]
  - [ 'prio2', 'trash', '104857600', 'reply' ]

gw_services:
  1_ping:
    ports:
      - [ 'icmp', 0, 'prio1' ]
  1_dns:
    ports:
      - [ 'udp', '53', 'prio1' ]
  1_ntp:
    ports:
      - [ 'udp', '123', 'prio1' ]
  1_http:
    ports:
      - [ 'tcp', '80', 'browse' ]
      - [ 'tcp', '443', 'browse' ]
  0_valve:
    sets:
      - [ 'udp', 'IPSET_GAME_VALVE', 'dst', '27015:28999', 'prio1' ]
  0_steam:
    ports:
      - [ 'udp', '27015:27030', 'prio1', '27005' ]
  0_lol:
    ports:
      - [ 'both', '5000:5500', 'prio1' ]
      - [ 'tcp', '2099', 'prio2' ]
      - [ 'tcp', '5222:5223', 'prio2' ]
      - [ 'tcp', '8088', 'prio2' ]
      - [ 'tcp', '8393:8400', 'browse' ]
    sets:
      - [ 'tcp', 'IPSET_GAME_LOL', 'dst', '80', 'prio2' ]
      - [ 'tcp', 'IPSET_GAME_LOL', 'dst', '443', 'prio2' ]
  0_ow:
    sets:
      - [ 'udp', 'IPSET_GAME_BLIZZ', 'dst', '12000:32000', 'prio1' ]
      - [ 'udp', 'IPSET_GAME_BLIZZ', 'dst', '3478:3479', 'prio2' ]
      - [ 'udp', 'IPSET_GAME_BLIZZ', 'dst', '5060:5062', 'prio2' ]
      - [ 'udp', 'IPSET_GAME_BLIZZ', 'dst', '6052', 'prio2' ]
      - [ 'tcp', 'IPSET_GAME_BLIZZ', 'dst', '6113', 'prio2' ]
  bdesert:
    ports:
      - [ 'tcp', '9991:9993', 'prio2' ]
  brawl:
    ports:
      - [ 'tcp', '23000:23010', 'prio2' ]
  bf:
    ports:
      - [ 'udp', '14000:14016', 'prio2' ]
      - [ 'udp', '22990:23006', 'prio2' ]
      - [ 'udp', '25200:25300', 'prio2' ]
      - [ 'udp', '3659', 'prio2' ]
      - [ 'tcp', '17502', 'prio2' ]
      - [ 'tcp', '22990', 'prio2' ]
      - [ 'tcp', '42127', 'prio2' ]
      - [ 'tcp', '9988', 'prio2' ]
      - [ 'tcp', '20000:20100', 'prio2' ]
  cod:
    ports:
      - [ 'udp', '28960:28965', 'prio1' ]
  eve:
    ports:
      - [ 'tcp', '2600', 'prio2' ]
  firefall:
    ports:
      - [ 'udp', '25000:25099', 'prio2' ]
  runescape:
    ports:
      - [ 'both', '43594:43595', 'prio2' ]
  rleague:
    ports:
      - [ 'udp', '7000:9000', 'prio1' ]
  gw2:
    ports:
      - [ 'tcp', '6112', 'prio2' ]
  grwild:
    ports:
      - [ 'udp', '3074:3083', 'prio2' ]
  h1z1:
    ports:
      - [ 'udp', '20040:20199', 'prio2' ]
  mc:
    ports:
      - [ 'both', '25561:25565', 'prio2' ]
  sc2hs:
    sets:
      - [ 'both', 'IPSET_GAME_BLIZZ', 'dst', '1119:1120', 'prio1' ]
  hon:
    ports:
      - [ 'tcp', '11031', 'prio2' ]
      - [ 'both', '11235', 'prio2' ]
  rift:
    ports:
      - [ 'tcp', '6520:6540', 'prio2' ]
  rust:
    ports:
      - [ 'udp', '28015', 'prio2' ]
  uplay:
    ports:
      - [ 'tcp', '14000', 'prio2' ]
      - [ 'tcp', '14008', 'prio2' ]
      - [ 'tcp', '14020:14024', 'prio2' ]
  wildstar:
    ports:
      - [ 'udp', '6600', 'prio2' ]
      - [ 'tcp', '23115', 'prio2' ]
      - [ 'tcp', '24000:24999', 'prio2' ]
  wot:
    ports:
      - [ 'udp', '20016', 'prio2' ]
      - [ 'udp', '32860:32864', 'prio2' ]
  wow:
    sets:
      - [ 'tcp', 'IPSET_GAME_BLIZZ', 'dst', '3724', 'prio1' ]

gw_ipsets:
  RFC1918:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  IPSET_GAME_BLIZZ:
    - 5.42.160.0/19
    - 12.129.222.0/23
    - 12.129.228.0/23
    - 12.129.236.0/23
    - 12.129.254.0/23
    - 12.130.244.0/22
    - 24.105.0.0/18
    - 37.244.0.0/18
    - 59.153.40.0/22
    - 62.115.244.0/22
    - 80.239.208.0/22
    - 103.4.114.0/23
    - 103.198.32.0/23
    - 137.221.64.0/18
    - 185.60.112.0/22
    - 195.12.244.0/22
    - 199.108.32.0/19
    - 202.9.66.0/23
  IPSET_GAME_LOL:
    - 8.23.24.0/23
    - 43.229.64.0/22
    - 59.100.79.128/25
    - 59.100.95.128/25
    - 66.151.33.0/24
    - 95.172.65.0/24
    - 103.240.226.0/23
    - 104.160.128.0/19
    - 117.52.101.0/24
    - 138.0.12.0/22
    - 162.249.72.0/21
    - 182.162.120.0/21
    - 185.40.64.0/22
    - 189.125.80.0/24
    - 189.125.169.0/24
    - 192.64.168.0/21
  IPSET_GAME_VALVE:
    - 45.121.184.0/22
    - 63.150.138.0/24
    - 103.10.124.0/23
    - 103.28.54.0/23
    - 143.137.146.0/24
    - 146.66.152.0/21
    - 153.254.86.0/24
    - 155.133.224.0/19
    - 162.254.192.0/21
    - 185.25.180.0/22
    - 190.216.121.0/24
    - 190.217.33.0/24
    - 192.69.96.0/22
    - 204.63.214.0/23
    - 205.185.194.0/24
    - 205.196.6.0/24
    - 208.64.200.0/22
    - 208.78.164.0/22

gw_priorities:
  prio1: 1
  prio2: 2
  browse: 3
  download: 4
  crew: 5
  trash: 6

gw_dscp:
  prio1: "0x22"
  prio2: "0x24"
  crew: "0x12"
  browse: "0x1a"
  download: "0x1c"
  trash: "0x01"
