---
- name: Nginx | Create Config Directories
  file:
    state: directory
    path: /etc/nginx/{{ item }}
  with_items:
    - conf.d
    - sites-enabled
    - sites-available

- name: Nginx | Render Configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Nginx | Render htpasswd
  template:
    src: htpasswd.j2
    dest: /et/nginx/htpasswd
  notify: reload nginx

- name: Nginx | Render Defaults
  template:
    src: nginx.default.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

- name: Nginx | Disable Default Site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  when: nginx_disable_default

- name: Nginx | Enable Default Site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
  when: not nginx_disable_default

- name: Nginx | Install Logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx
    mode: 0644

- name: Nginx | Enable Hourly Logrotate
  template:
    src: logrotate.hourly.j2
    dest: /etc/cron.hourly/logrotate
