---
- name: Depot | Log Directories
  file:
    state: directory
    path: "{{ depot_logdir }}/{{ item.key }}"
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
    recurse: true
  with_dict: "{{ depot_sites }}"

- name: Depot | Render Global Parameters
  template:
    src: depot.conf.j2
    dest: /etc/nginx/conf.d/depot.conf
  notify: reload nginx

- name: Depot | Config Directory
  file:
    state: directory
    path: /etc/nginx/depot

- name: Depot | Render Proxy Parameters
  template:
    src: "includes/{{ item }}.conf.j2"
    dest: "/etc/nginx/depot/{{ item }}.conf"
  with_items:
    - proxy-base
    - proxy-cache
    - proxy-pass
    - proxy-slice
    - proxy-noslice
  notify: reload nginx

- name: Depot | Render Site Templates
  template:
    src: "{{ item.key }}.site.j2"
    dest: "/etc/nginx/sites-available/depot-{{ item.key }}"
  with_dict: "{{ depot_sites }}"
  notify: reload nginx
  tags: [ 'spoof' ]

- name: Depot | Install Logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/nginx-depot
