---
- name: elastic | Install OpenJDK
  apt:
    name: openjdk-8-jre-headless
  tags: [ 'packages' ]

- name: elastic | Install elasticsearch
  apt:
    name: elasticsearch
  tags: [ 'packages' ]

- name: elastic | Render elasticsearch.yml
  template:
    src: es.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: elastic | Render jvm.options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
  notify: restart es

- name: elastic | Start Service
  service:
    name: elasticsearch
    state: started
    enabled: true
